### ISSUE TITLE
Initial Data acquisition

### ISSUE THREAD

**Issue by JDatPNW** [JDatPNW/TeamBappiTeam#2]
Find and test a basic way to gather data for the project.

- [x] WebToon #14 
- [x] Anime #10 
- [x] ~~Manga~~ Will not ben considered in initial early stages

**Comment by jhs-164179** [comment]
The file was downloaded and sliced using Webtoon Downloader (https://github.com/Zehina/Webtoon-Downloader), and the characters and speech bubbles were removed using the site's(https://www.photoroom.com/tools/remove-object-from-photo) functions.

The data is in the jhs_dataset branch.

**Comment by JDatPNW** [comment]
#10

**Comment by JDatPNW** [comment]
> The file was downloaded and sliced using Webtoon Downloader (https://github.com/Zehina/Webtoon-Downloader), and the characters and speech bubbles were removed using the site's(https://www.photoroom.com/tools/remove-object-from-photo) functions.
> 
> The data is in the jhs_dataset branch.

We might want to consider not uploading any data, but only the code that generates it and instructions on how to do it.

**Comment by JDatPNW** [comment]
#12

**Comment by JDatPNW** [comment]
#14
